Code structure
Logan-dlp/Logan-ProjetRappel2emeAnnee pull request #1
Opened 2024-02-29 16:27 UTC by Logan-dlp

2024-03-11 20:49 UTC, GuitoonDev requested changes
Il y a toujours certains des problèmes relevés lors de l'issue (https://github.com/Logan-dlp/Logan-ProjetRappel2emeAnnee/issues/2) sur le projet en lui même (que je te demanderais de corriger dans une branche à part qui servira de correction du projet s'il te plait).

Et quelques petits retours sur la structure.

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/Inventory/Inventory.cs
> +    }
Tu ne supprimes jamais rien de ton inventaire ?

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/Items/InventoryItem.cs
> +        base._scriptableItem.Sprite = _spriteRenderer.sprite;
Si la variable `_scriptableItem` est `protected`, tu n'as pas besoin de passer par le mot-clé `base`. Il est facultatif.

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/Items/ScriptableItem.cs
> +    [SerializeField] private Sprite _sprite;
ça je ne comprends pas pourquoi il passe en dessous de l'accesseur.

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/Movements/PlayerMovement.cs
Je ne vois toujours pas l'intérêt de faire le déplacement du player dans le FixedUpdate vu qu'il n'y pas de physique à gérer au niveau du mouvement.

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/UI/Display/IDisplay.cs
> +}
Attention à l'usage. Si une interface est définie mais qu'elle n'est pas utilisée (comme celle de IPowerUP) elle n'a pas vraiment d'intérêt à exister.

Autant la rajouter si jamais le besoin est présent. Pas avant.

2024-03-11 20:49 UTC, GuitoonDev commented on Assets/_Core/Scripts/Movements/IMovement.cs
> +}
Attention à l'usage. Si une interface est définie mais qu'elle n'est pas utilisée (comme celle de IPowerUP) elle n'a pas vraiment d'intérêt à exister.

Autant la rajouter si jamais le besoin est présent. Pas avant.

2024-03-15 10:55 UTC, Logan-dlp commented on Assets/_Core/Scripts/Movements/PlayerMovement.cs
Je changerais ça aprés les merges de Build-Android pour pouvoir réadapté en même temp sur la version PC et Mobile

2024-03-17 12:54 UTC, GuitoonDev requested changes
Ok mais en attente du dernier changement.

2024-03-17 12:54 UTC, GuitoonDev commented on Assets/_Core/Scripts/Movements/PlayerMovement.cs
Ok je valide les changements mais je laisse en Request Changes tant que je point n'est pas modifié.

2024-03-24 20:52 UTC, GuitoonDev approved these changes

2024-03-25 09:14 UTC, merged