Serialization
Logan-dlp/Logan-ProjetRappel2emeAnnee pull request #3
Opened 2024-03-11 09:48 UTC by Logan-dlp

2024-03-11 21:15 UTC, GuitoonDev requested changes
Il y a des usages de dictionnaires qui est maladroit, attention aussi à continuer à respecter la structure des DTO pour de nouvelles classes.

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/ScriptableObject/Listener/ScriptableIntListener.cs
> +        _callbacks?.Invoke(number);
Je ne comprends pas pourquoi faire une méthode qui permet d'_invoke_ `callbacks` sans se baser sur le `ScriptableObject` que le _listener_ est sensé écouter.

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/ScriptableObject/Listener/ScriptableIntListener.cs
En déplaçant les listeners dans le dossier `ScriptableObject`, tu places des `MonoBehaviour` à l'intérieur. Ce qui donne une impression d'incohérence dans le rangement.

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> +            LoadVariableStorage();
_(vu à plusieurs endroits)_
Donc tu décides de remplir le contenu de tous tes dictionnaires à chaque fois que tu veux accéder ou modifier une variable ?
Quel est ton but ?

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> +            foreach (KeyValuePair<string,bool> keyValuePair in _saveBools)
_(vu à d'autres endroits)_
Attention, ton usage actuel des dictionnaires est très **très** sous optimal !

Il y a des moyens bien plus simples d'accéder à ce que tu veux faire que de devoir parcourir les éléments de cette manière !
Je te conseille de regarder la documentation du C# liée aux dictionnaires un peu plus en détail.

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> +    private void SaveVariableStorage()
Le but de l'exercice est de ne produire qu'un seul fichier de sauvegarde pour gagner en simplicité.

Il faut intégrer le `VariableStorage` dans le `SaveSystem`

2024-03-11 21:15 UTC, GuitoonDev commented on Assets/_Core/Scripts/Save/DTO/SaveVarialbleStorage.cs
C'est une classe qui sert à stocker de la donnée qui est dans le dossier DTO mais c'est pas un DTO et il n'hérite pas de DTO ? 🤔

2024-03-12 09:21 UTC, Logan-dlp commented on Assets/_Core/Scripts/ScriptableObject/Listener/ScriptableIntListener.cs
> +        _callbacks?.Invoke(number);
J'ai pas compris il le prend en charge dans le onEnable() donc il est basé sur le ScriptableObject non ?

2024-03-12 09:23 UTC, Logan-dlp commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> +            LoadVariableStorage();
Je voulais load avant pour rafraichir tout les dictionnaires

2024-03-17 12:48 UTC, GaetanCamelia requested changes
Attention, tu as un missing script sur ton gameObject de Save System :
![image](https://github.com/Logan-dlp/Logan-ProjetRappel2emeAnnee/assets/162618531/e9efef3c-7ae3-47bb-aaca-11a228bcbe4d)

+ d'autres reviews plus bas

2024-03-17 12:48 UTC, GaetanCamelia commented on Assets/_Core/Scripts/Save/SaveSystem.cs
Ligne 10 : la variable `instance` d'un singleton ne doit jamais être accessible en écriture. Seulement en lecture !

2024-03-17 12:48 UTC, GaetanCamelia commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> -    private static VariableStorageSystem _instance;
D'accord mais en l'état, ton variable system, ne peut être appelé par personne pour y ajouter ou utiliser une variable qu'elle contiendrait.

2024-03-17 12:48 UTC, GaetanCamelia commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
>      private Dictionary<string, bool> _saveBools = new();
Cette version me convient mais attention, tu peux avoir le même nom de variable pour des types de variables différents.

Tu peux avoir un "lifeValue" en `float` ET `string` ET `bool`.

2024-03-17 12:48 UTC, GaetanCamelia commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
> +        return new()
Cette ligne ne me convient pas car on ne peut pas déduire le type de la variable sur la ligne où on fait le `new()`.

2024-03-21 20:28 UTC, GuitoonDev approved these changes

2024-03-21 20:28 UTC, GuitoonDev commented on Assets/_Core/Scripts/Save/VariableStorageSystem.cs
Je vois ce que tu veux faire et c'est ok pour moi.
Mais tu devrais regarder du côté du HashSet pour vérifier l'existence des noms de variables.

2024-03-22 09:00 UTC, merged