Build android
Logan-dlp/Logan-ProjetRappel2emeAnnee pull request #4
Opened 2024-03-15 10:35 UTC by Logan-dlp

2024-03-17 11:18 UTC, Logan-dlp commented
Mdp : 070904

2024-03-17 14:02 UTC, GuitoonDev requested changes
Quand je build & run sur mon téléphone en récupérant le projet, je ne peux pas déplacer le player.

Il n'y a aucun bouton ou stick visible sur l'écran.

2024-03-18 18:55 UTC, Logan-dlp commented
Je comprends pas j'ai essayé de rebuil sur mon androïde et tout fonctionne et le script pour lancer les scènes de départ est bien là, on pourra voir ça mercredi ?

2024-03-24 17:40 UTC, GuitoonDev approved these changes
J'ai pu build et ça fonctionne pour moi donc ok.

Par contre, pour avoir un peu vu l'état de ton projet où il y a vraiment beaucoup beaucoup de scripts sur certains gameObjects, je suis inquiet de la facilité de compréhension que pourrait avoir une nouvelle personne qui arriverait sur le projet (ou un futur si tu comptes réutiliser la même structure.

L'évènementiel c'est cool mais ça peut vite devenir un piège si on commence à en utiliser tellement qu'on arrive plus à comprendre ce que l'on est sensé faire avec.

2024-03-25 08:59 UTC, merged